### ISSUE TITLE
Failed to check if track already exists locally.

### ISSUE THREAD

**Issue by Cryptical1** [Sorrow446/Nugs-Downloader#48]
Not seen this before. The track plays fine on the site. Any way to force this track?
Item 1 of 1:
Goose - 05/26/24 Solshine: A Music & Arts Reverie, Chillicothe, IL
Track already exists locally.
Track already exists locally.
Track already exists locally.
Track already exists locally.
Track already exists locally.
Track already exists locally.
Failed to check if track already exists locally.
Track failed.
CreateFile D:Goose - 05_26_24 Solshine_ A Music & Arts Reverie, Chillicothe, IL\07. Chillicothe Soundcheck Jam  .flac: The filename, directory name, or volume label syntax is incorrect.
Track already exists locally.
Track already exists locally.
Track already exists locally.
Track already exists locally.
Track already exists locally.
Track already exists locally.

**Comment by Sorrow446** [comment]
Need a link please.

**Comment by Cryptical1** [comment]
Sorry 'bout that...
https://play.nugs.net/release/37172

**Comment by Sorrow446** [comment]
Happens here too on the same track on Windows, there's something in the filename it doesn't like. Gotta brb for like an hour, then I'll take a look.

**Comment by Sorrow446** [comment]
Done.

**Comment by Cryptical1** [comment]
Still not getting the badly named track. I've updated Go and replaced the downloader files with the latest but no luck. Am I missing something?

**Comment by Sorrow446** [comment]
What? I've pushed the fix to the source code. The title had a tab at the end of it for some reason.

**Comment by Cryptical1** [comment]
Are there instructions on how to run from the source code?

**Comment by Sorrow446** [comment]
1. Install Go https://go.dev/doc/install.
2. Open Command Prompt in script's folder. CD in manually or just input "cmd" into the address bar.
3. `go run . <your args>`

**Comment by Cryptical1** [comment]
No matter what I try, I get:
imports iter: build constraints exclude all Go files in C:\Program Files\Go\src\iter

**Comment by Sorrow446** [comment]
Move your scripts folder to your downloads folder or something. Don't have to call Go from there as the installer adds it to path :p.

**Comment by Cryptical1** [comment]
I've been pouring through Stack Overflow for a couple of days to try and figure this out, but no matter where I move the files I get the same:  imports iter: build constraints exclude all Go files in C:\Program Files\Go\src\iter
Runs fine with the binary though.

**Comment by Sorrow446** [comment]
Damn, no problem. It's always worked out the box for me.
https://gofile.io/d/RirkBp

**Comment by Cryptical1** [comment]
I really, really appreciate that, and I'm going to figure out the issue. I can't stand not knowing why something isn't working.

**Comment by Sorrow446** [comment]
You're welcome.

Let me know if any of these help.
`go clean -cache`

Delete `go.mod` and `go.sum`, then do `go mod init main && go mod tidy`.
